# Site settings
title: Tersine Mühendisler Odası
email: ttmo [at] protonmain [.] com
url: https://ttmo-o.github.io/
description: "Amaç: Türkiye'deki rev eng'leri birleştirmek."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: TTMO

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/__TTMO__
  - title: github
    url: https://github.com/ttmo-O
  - title: telegram
    url: https://t.me/ttmo_O

# Build settings
markdown: kramdown
permalink: pretty
